### ISSUE TITLE
extra_html_url' option is deprecated

### ISSUE THREAD

**Issue by markbooth73** [pkozul/ha-floorplan#100] opened 2020-07-23 08:16 UTC
After Updating to  0.113.0 I am getting this error

Log Details (WARNING)
Logger: homeassistant.components.frontend
Source: helpers/config_validation.py:709
Integration: Home Assistant Frontend (documentation, issues)
First occurred: 8:59:56 (1 occurrences)
Last logged: 8:59:56

The 'extra_html_url' option is deprecated, please remove it from your configuration. This option will become invalid in version 0.115

The only reference to this appears in my configuration.yaml
```
frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
```

**Comment by RoldyBuffalo** [comment] 2020-07-23 09:05
Duplicate of issue #99

**Comment by pkozul** [comment] 2021-02-09 22:07
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan

**Closed as completed by pkozul** 2021-02-09 22:07 UTC
